name: Create iframe index.html for published Google Doc

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5-7'   # Midnight UTC (Fri–Sun)
    - cron: '0 12 * * 5-7'  # Noon UTC (Fri–Sun)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create index.html with iframe
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Clarkston Ward Program</title>
            <style>
              html, body {
                margin: 0;
                padding: 0;
                height: 100%;
                overflow: hidden;
              }
              iframe {
                border: none;
                width: 100%;
                height: 100%;
              }
            </style>
          </head>
          <body>
            <iframe src="https://docs.google.com/document/d/e/2PACX-1vTWu0kV3LI2k21O2iPNr41qkUrSg_3SPEujWjlAsVwqCQOqCRFLHB4eArr9AscqNxd9PpJUQg5B6k0k/pub?embedded=true"></iframe>
          </body>
          </html>
          EOF

      - name: Configure Git
        run: |
          git config user.name "Auto Publisher"
          git config user.email "autopub@users.noreply.github.com"

      - name: Commit and push if changed
        run: |
          git add index.html
          if ! git diff --cached --quiet; then
            git commit -m "📄 Regenerated iframe-based index.html"
            git push
          else
            echo "No changes to commit"
          fi
